### ISSUE TITLE
Register jni method

### ISSUE THREAD

**Issue by nadavgr** [nayobix/add-new-hardware-hal-android-5-lollipop#1]
Hi,
it fails on boot when trying to load the register jni method.
if fails on services/core/jni:
register_android_server_xxxService(...) {
... jniRegisterNativeMethods(env, "com/android/server/xxx/xxxService",.....)
}

sais in runtime that cant find class com/android/server/xxx/xxxService

do you know how to solve this issue?
tried on android 6.0.1

**Comment by nayobix** [comment]
Hi,

Please check http://stackoverflow.com/questions/38851854/creating-system-service-in-android

Thanks!
